# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import anomaly_pb2 as anomaly__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in anomaly_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnomalyDetectorServiceStub(object):
    """gRPC contracts
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeAnomalyProject = channel.unary_unary(
                '/skavl.anomaly.v1.AnomalyDetectorService/DescribeAnomalyProject',
                request_serializer=anomaly__pb2.DescribeAnomalyProjectRequest.SerializeToString,
                response_deserializer=anomaly__pb2.DescribeAnomalyProjectResponse.FromString,
                _registered_method=True)
        self.DetectAnomalySet = channel.unary_unary(
                '/skavl.anomaly.v1.AnomalyDetectorService/DetectAnomalySet',
                request_serializer=anomaly__pb2.DetectAnomalySetRequest.SerializeToString,
                response_deserializer=anomaly__pb2.DetectAnomalySetResponse.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/skavl.anomaly.v1.AnomalyDetectorService/GetProgress',
                request_serializer=anomaly__pb2.GetProgressRequest.SerializeToString,
                response_deserializer=anomaly__pb2.GetProgressResponse.FromString,
                _registered_method=True)
        self.StopAnalysis = channel.unary_unary(
                '/skavl.anomaly.v1.AnomalyDetectorService/StopAnalysis',
                request_serializer=anomaly__pb2.StopAnalysisRequest.SerializeToString,
                response_deserializer=anomaly__pb2.StopAnalysisResponse.FromString,
                _registered_method=True)


class AnomalyDetectorServiceServicer(object):
    """gRPC contracts
    """

    def DescribeAnomalyProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectAnomalySet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyDetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeAnomalyProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeAnomalyProject,
                    request_deserializer=anomaly__pb2.DescribeAnomalyProjectRequest.FromString,
                    response_serializer=anomaly__pb2.DescribeAnomalyProjectResponse.SerializeToString,
            ),
            'DetectAnomalySet': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalySet,
                    request_deserializer=anomaly__pb2.DetectAnomalySetRequest.FromString,
                    response_serializer=anomaly__pb2.DetectAnomalySetResponse.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=anomaly__pb2.GetProgressRequest.FromString,
                    response_serializer=anomaly__pb2.GetProgressResponse.SerializeToString,
            ),
            'StopAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAnalysis,
                    request_deserializer=anomaly__pb2.StopAnalysisRequest.FromString,
                    response_serializer=anomaly__pb2.StopAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skavl.anomaly.v1.AnomalyDetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skavl.anomaly.v1.AnomalyDetectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnomalyDetectorService(object):
    """gRPC contracts
    """

    @staticmethod
    def DescribeAnomalyProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.anomaly.v1.AnomalyDetectorService/DescribeAnomalyProject',
            anomaly__pb2.DescribeAnomalyProjectRequest.SerializeToString,
            anomaly__pb2.DescribeAnomalyProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectAnomalySet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.anomaly.v1.AnomalyDetectorService/DetectAnomalySet',
            anomaly__pb2.DetectAnomalySetRequest.SerializeToString,
            anomaly__pb2.DetectAnomalySetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.anomaly.v1.AnomalyDetectorService/GetProgress',
            anomaly__pb2.GetProgressRequest.SerializeToString,
            anomaly__pb2.GetProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.anomaly.v1.AnomalyDetectorService/StopAnalysis',
            anomaly__pb2.StopAnalysisRequest.SerializeToString,
            anomaly__pb2.StopAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
