# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import report_pb2 as report__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in report_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportServiceStub(object):
    """Service for generating reports from anomaly data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateReportUnclassified = channel.unary_unary(
                '/skavl.report.v1.ReportService/GenerateReportUnclassified',
                request_serializer=report__pb2.ReportGenerationRequest.SerializeToString,
                response_deserializer=report__pb2.ReportGenerationResponse.FromString,
                _registered_method=True)
        self.GenerateReportClassified = channel.unary_unary(
                '/skavl.report.v1.ReportService/GenerateReportClassified',
                request_serializer=report__pb2.ReportGenerationRequest.SerializeToString,
                response_deserializer=report__pb2.ReportGenerationResponse.FromString,
                _registered_method=True)


class ReportServiceServicer(object):
    """Service for generating reports from anomaly data
    """

    def GenerateReportUnclassified(self, request, context):
        """Generates a unclassified report based on the provided anomaly sets and metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReportClassified(self, request, context):
        """Generates a classified report based on the provided anomaly sets and metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateReportUnclassified': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReportUnclassified,
                    request_deserializer=report__pb2.ReportGenerationRequest.FromString,
                    response_serializer=report__pb2.ReportGenerationResponse.SerializeToString,
            ),
            'GenerateReportClassified': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReportClassified,
                    request_deserializer=report__pb2.ReportGenerationRequest.FromString,
                    response_serializer=report__pb2.ReportGenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skavl.report.v1.ReportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skavl.report.v1.ReportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportService(object):
    """Service for generating reports from anomaly data
    """

    @staticmethod
    def GenerateReportUnclassified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.report.v1.ReportService/GenerateReportUnclassified',
            report__pb2.ReportGenerationRequest.SerializeToString,
            report__pb2.ReportGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReportClassified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.report.v1.ReportService/GenerateReportClassified',
            report__pb2.ReportGenerationRequest.SerializeToString,
            report__pb2.ReportGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
