# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shutdown.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'shutdown.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshutdown.proto\x12\x0eskavl.shutdown\"\x11\n\x0fShutdownRequest\"\x12\n\x10ShutdownResponse2`\n\x0fShutdownService\x12M\n\x08Shutdown\x12\x1f.skavl.shutdown.ShutdownRequest\x1a .skavl.shutdown.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shutdown_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHUTDOWNREQUEST']._serialized_start=34
  _globals['_SHUTDOWNREQUEST']._serialized_end=51
  _globals['_SHUTDOWNRESPONSE']._serialized_start=53
  _globals['_SHUTDOWNRESPONSE']._serialized_end=71
  _globals['_SHUTDOWNSERVICE']._serialized_start=73
  _globals['_SHUTDOWNSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
