# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tiler_pb2 as tiler__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tiler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TilerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeSource = channel.unary_unary(
                '/skavl.tiler.v1.TilerService/DescribeSource',
                request_serializer=tiler__pb2.DescribeSourceRequest.SerializeToString,
                response_deserializer=tiler__pb2.DescribeSourceResponse.FromString,
                _registered_method=True)
        self.PlanViewport = channel.unary_unary(
                '/skavl.tiler.v1.TilerService/PlanViewport',
                request_serializer=tiler__pb2.PlanViewportRequest.SerializeToString,
                response_deserializer=tiler__pb2.PlanViewportResponse.FromString,
                _registered_method=True)


class TilerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DescribeSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanViewport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TilerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeSource,
                    request_deserializer=tiler__pb2.DescribeSourceRequest.FromString,
                    response_serializer=tiler__pb2.DescribeSourceResponse.SerializeToString,
            ),
            'PlanViewport': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanViewport,
                    request_deserializer=tiler__pb2.PlanViewportRequest.FromString,
                    response_serializer=tiler__pb2.PlanViewportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skavl.tiler.v1.TilerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skavl.tiler.v1.TilerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TilerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribeSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.tiler.v1.TilerService/DescribeSource',
            tiler__pb2.DescribeSourceRequest.SerializeToString,
            tiler__pb2.DescribeSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanViewport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/skavl.tiler.v1.TilerService/PlanViewport',
            tiler__pb2.PlanViewportRequest.SerializeToString,
            tiler__pb2.PlanViewportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
